apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: acs-init-bundle
  namespace: stackrox
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli@sha256:d5b40b3b0e2b843e13710f0bdc6b1174a265f364534a67f2136c710effb9465f
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/pull
              set -x
              echo ""
              echo "========================"
              echo -e "Waiting for ACS Central service\n"
              until [ $(curl -s -k -o /dev/null -w "%{http_code}" https://central) -eq 200 ]; do echo -n "."; sleep 15; done
              echo -e "Online!\n"
              #yum install -qy jq
              echo "Generating the init-bundle..."
              AUTH=$(echo "admin:$ACS_PASSWORD" | tr -d \\n | base64)
              INIT_BUNDLE=$(curl -X POST -k --header "Authorization: Basic ${AUTH}" https://central/v1/cluster-init/init-bundles --data '{"name": "'"$ACS_SECURED_CLUSTER"'"}')
              echo $INIT_BUNDLE | python3 -c "import sys, json; print(json.load(sys.stdin)['kubectlBundle'])" | base64 -d > /tmp/init-bundle.yaml
              echo "Applying the init bundle secrets..."
              oc apply -f /tmp/init-bundle.yaml
              echo "========================"
          imagePullPolicy: Always
          name: acs-init-task
          env:
          - name: ACS_PASSWORD
            value: "redhat01"
          - name: ACS_SECURED_CLUSTER
            value: "local-cluster"
      restartPolicy: OnFailure
      serviceAccount: acs-gitops
      serviceAccountName: acs-gitops
      terminationGracePeriodSeconds: 30